---
branches:
  except:
    - master
language: python
sudo: required
dist: xenial
python: "3.7"
before_install:
  - nvm install 10
install:
  - pip install --requirement=requirements.txt
  - npm ci
script:
  - npm test --silent
  - ./bootstrap/symlink
deploy:
  skip_cleanup: true
  provider: script
  script: meta/travis-automerge.bash
  "on":
    branch: dev
notifications:
  email:
    - travis@davidosomething.com
