---
branches:
  except:
    - master
sudo: false
addons:
  apt:
    packages:
      - shellcheck
language: python
os:
  - linux
python:
  - '2.7'
before_install:
  - nvm install --lts
script:
  - tox
  - npm test --silent
deploy:
  skip_cleanup: true
  provider: script
  script: meta/travis-automerge.bash
  "on":
    branch: dev
notifications:
  email:
    - travis@davidosomething.com
